feat: add debug on workflow

diff --git a/.github/workflows/dev-testflight.yaml b/.github/workflows/dev-testflight.yaml
--- a/.github/workflows/dev-testflight.yaml
+++ b/.github/workflows/dev-testflight.yaml
@@ -28,6 +28,13 @@ jobs:
           bundler-cache: true
           working-directory: SampaiTitik
 
+      - name: Debug - check key file
+        # working-directory: SampaiTitik
+        run: |
+          pwd
+          ls -la
+          ls -la asc_api_key.p8 || echo "FILE NOT FOUND"
+
       - name: Decode App Store Connect API Key
         run: echo "${{ secrets.ASC_KEY_CONTENT }}" | base64 --decode > asc_api_key.p8
 
